["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
naming = ["src/naming/main.cairo"]
pricing = ["src/pricing/main.cairo"]
proxy = ["lib/cairo_contracts/src/openzeppelin/upgrades/presets/Proxy.cairo"]

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src"]
