[project]
protostar-version = "0.9.0"
lib-path = "lib"
cairo-path = ["lib", "./lib/cairo_contracts/src", "./lib/starknetid"]

[contracts]
naming = ["src/naming/main.cairo"]
pricing = ["src/pricing/main.cairo"]
proxy = ["lib/cairo_contracts/src/openzeppelin/upgrades/presets/Proxy.cairo"]
